#eureka server服务端口
server:
  port: 8761
spring:
  application:
    name: sd-cloud-eureka-server # 应用名称，应用名称会在Eureka中作为服务名称

    # eureka 客户端配置（和Server交互），Eureka Server 其实也是一个Client
eureka:
  instance:
    hostname: SdCloudEurekaServerA  # 当前eureka实例的主机名
  client:
    service-url: # 配置客户端所交互的Eureka Server的地址
      defaultZone: http://SdCloudEurekaServerB:8762/eureka
    register-with-eureka: true  #  集群模式下可以改成true
    fetch-registry: true         #  集群模式下可以改成true

